=== SolWayward/Bannerlord.Commander/Bannerlord.Commander/schemas/gauntletui.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <!-- Root Elements -->
  <xs:element name="Prefab" type="PrefabType"/>
  <xs:element name="Window" type="WindowType"/>
  <xs:element name="Brushes" type="BrushesType"/>
  
  <!-- Complex Types -->
  <xs:complexType name="BrushesType">
    <xs:sequence>
      <xs:element name="Brush" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Layers" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="BrushLayer" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:attribute name="Name" type="xs:string" use="required"/>
                      <xs:attribute name="Sprite" type="xs:string"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="Styles" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Style" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="BrushLayer" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:attribute name="Name" type="xs:string" use="required"/>
                            <xs:attribute name="AlphaFactor" type="xs:float"/>
                            <xs:attribute name="Color" type="xs:string"/>
                            <xs:attribute name="ColorFactor" type="xs:float"/>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                      <xs:attribute name="Name" type="xs:string" use="required"/>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="SoundProperties" minOccurs="0">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="EventSounds" minOccurs="0">
                    <xs:complexType>
                      <xs:sequence>
                        <xs:element name="EventSound" minOccurs="0" maxOccurs="unbounded">
                          <xs:complexType>
                            <xs:attribute name="EventName" type="xs:string" use="required"/>
                            <xs:attribute name="Audio" type="xs:string" use="required"/>
                          </xs:complexType>
                        </xs:element>
                      </xs:sequence>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="Name" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="PrefabType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Parameters" type="ParametersType"/>
      <xs:element name="Window" type="WindowType"/>
      <xs:element name="Widget" type="WidgetType"/>
      <xs:element name="Constants" type="ConstantsType"/>
    </xs:choice>
  </xs:complexType>
  
  <xs:complexType name="ParametersType">
    <xs:sequence>
      <xs:element name="Parameter" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="Name" type="xs:string" use="required"/>
          <xs:attribute name="Type" type="xs:string" use="required"/>
          <xs:attribute name="Default" type="xs:string"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="ConstantsType">
    <xs:sequence>
      <xs:element name="Constant" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:attribute name="Name" type="xs:string" use="required"/>
          <xs:attribute name="Value" type="xs:string" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="WindowType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="WidgetElements"/>
    </xs:choice>
    <xs:attributeGroup ref="CommonAttributes"/>
  </xs:complexType>
  
  <xs:complexType name="WidgetType" mixed="true">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Children" type="ChildrenType"/>
      <xs:element name="ItemTemplate" type="ItemTemplateType"/>
      <xs:group ref="WidgetElements"/>
    </xs:choice>
    <xs:attributeGroup ref="CommonAttributes"/>
  </xs:complexType>
  
  <xs:complexType name="ChildrenType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="WidgetElements"/>
    </xs:choice>
  </xs:complexType>
  
  <xs:complexType name="ItemTemplateType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:group ref="WidgetElements"/>
    </xs:choice>
  </xs:complexType>
  
  <!-- Widget Elements Group -->
  <xs:group name="WidgetElements">
    <xs:choice>
      <xs:element name="Widget" type="WidgetType"/>
      <xs:element name="ListPanel" type="WidgetType"/>
      <xs:element name="GridWidget" type="WidgetType"/>
      <xs:element name="ButtonWidget" type="WidgetType"/>
      <xs:element name="TabToggleWidget" type="WidgetType"/>
      <xs:element name="TextWidget" type="WidgetType"/>
      <xs:element name="RichTextWidget" type="WidgetType"/>
      <xs:element name="ImageWidget" type="WidgetType"/>
      <xs:element name="BrushWidget" type="WidgetType"/>
      <xs:element name="ScrollablePanel" type="WidgetType"/>
      <xs:element name="EditableTextWidget" type="WidgetType"/>
      <xs:element name="SliderWidget" type="WidgetType"/>
      <xs:element name="CheckboxWidget" type="WidgetType"/>
      <xs:element name="DropdownWidget" type="WidgetType"/>
      <xs:element name="NavigationScopeTargeter" type="WidgetType"/>
      <xs:element name="TooltipWidget" type="WidgetType"/>
      <xs:element name="VideoWidget" type="WidgetType"/>
      <xs:element name="CircleWidget" type="WidgetType"/>
      <xs:element name="MaskedTextureWidget" type="WidgetType"/>
      <xs:element name="FillBarWidget" type="WidgetType"/>
      <xs:element name="MinMaxSliderWidget" type="WidgetType"/>
      <xs:element name="AutoHideScrollBar" type="WidgetType"/>
      <xs:element name="NavigationAutoScrollWidget" type="WidgetType"/>
      <xs:element name="TabbedPanel" type="WidgetType"/>
      <xs:element name="Tree" type="WidgetType"/>
      <xs:element name="Container" type="WidgetType"/>
      <xs:element name="ScrollbarWidget" type="WidgetType"/>
      <xs:element name="ImageIdentifierWidget" type="WidgetType"/>
      <xs:element name="CommanderEquipmentSlotWidget" type="WidgetType"/>
      <xs:element name="CharacterTableauWidget" type="WidgetType"/>
      <xs:element name="InventoryEquippedItemSlot" type="WidgetType"/>
      <xs:element name="HeroInfoColumn" type="WidgetType"/>
      <xs:element name="HeroCharacterColumn" type="WidgetType"/>
      <xs:element name="HeroSkillsColumn" type="WidgetType"/>
      <xs:element name="SkillIconVisualWidget" type="WidgetType"/>
      <xs:element name="CommanderHeaderBar" type="WidgetType"/>
      <xs:element name="CommanderModeTabsBar" type="WidgetType"/>
      <xs:element name="CommanderFooterBar" type="WidgetType"/>
      <xs:element name="CommanderHeroListPanel" type="WidgetType"/>
    </xs:choice>
  </xs:group>
  
  <!-- Common Attributes -->
  <xs:attributeGroup name="CommonAttributes">
    <!-- Core Properties -->
    <xs:attribute name="Id" type="xs:string"/>
    <xs:attribute name="DataSource" type="xs:string"/>
    <xs:attribute name="DoNotAcceptEvents" type="xs:boolean"/>
    <xs:attribute name="DoNotPassEventsToChildren" type="xs:boolean"/>
    <xs:attribute name="IsEnabled" type="BooleanOrBindingType"/>
    <xs:attribute name="IsVisible" type="BooleanOrBindingType"/>
    <xs:attribute name="IsHidden" type="BooleanOrBindingType"/>
    
    <!-- Size Properties -->
    <xs:attribute name="WidthSizePolicy" type="SizePolicyType"/>
    <xs:attribute name="HeightSizePolicy" type="SizePolicyType"/>
    <xs:attribute name="SuggestedWidth" type="xs:float"/>
    <xs:attribute name="SuggestedHeight" type="xs:float"/>
    <xs:attribute name="MinWidth" type="xs:float"/>
    <xs:attribute name="MinHeight" type="xs:float"/>
    <xs:attribute name="MaxWidth" type="xs:float"/>
    <xs:attribute name="MaxHeight" type="xs:float"/>
    <xs:attribute name="ScaledSuggestedWidth" type="xs:float"/>
    <xs:attribute name="ScaledSuggestedHeight" type="xs:float"/>
    
    <!-- Alignment Properties -->
    <xs:attribute name="HorizontalAlignment" type="AlignmentType"/>
    <xs:attribute name="VerticalAlignment" type="AlignmentType"/>
    
    <!-- Margin and Padding -->
    <xs:attribute name="MarginTop" type="xs:float"/>
    <xs:attribute name="MarginBottom" type="xs:float"/>
    <xs:attribute name="MarginLeft" type="xs:float"/>
    <xs:attribute name="MarginRight" type="xs:float"/>
    <xs:attribute name="PaddingTop" type="xs:float"/>
    <xs:attribute name="PaddingBottom" type="xs:float"/>
    <xs:attribute name="PaddingLeft" type="xs:float"/>
    <xs:attribute name="PaddingRight" type="xs:float"/>
    
    <!-- Position -->
    <xs:attribute name="PositionXOffset" type="xs:float"/>
    <xs:attribute name="PositionYOffset" type="xs:float"/>
    <xs:attribute name="UpdateChildrenStates" type="BooleanOrBindingType"/>
    
    <!-- Visual Properties -->
    <xs:attribute name="Brush" type="xs:string"/>
    <xs:attribute name="Sprite" type="xs:string"/>
    <xs:attribute name="Color" type="xs:string"/>
    <xs:attribute name="AlphaFactor" type="xs:float"/>
    <xs:attribute name="ColorFactor" type="xs:float"/>
    <xs:attribute name="HueFactor" type="xs:float"/>
    <xs:attribute name="SaturationFactor" type="xs:float"/>
    <xs:attribute name="ValueFactor" type="xs:float"/>
    
    <!-- Text Properties -->
    <xs:attribute name="Text" type="xs:string"/>
    <xs:attribute name="FontSize" type="xs:float"/>
    <xs:attribute name="TextHorizontalAlignment" type="AlignmentType"/>
    <xs:attribute name="TextVerticalAlignment" type="AlignmentType"/>
    
    <!-- Brush Override Properties (using dot notation) -->
    <xs:attribute name="Brush.FontSize" type="xs:float"/>
    <xs:attribute name="Brush.TextHorizontalAlignment" type="AlignmentType"/>
    <xs:attribute name="Brush.TextVerticalAlignment" type="AlignmentType"/>
    <xs:attribute name="Brush.TextColor" type="xs:string"/>
    <xs:attribute name="Brush.Color" type="xs:string"/>
    
    <!-- ListPanel Properties -->
    <xs:attribute name="LayoutImp.LayoutMethod" type="LayoutMethodType"/>
    <xs:attribute name="StackLayout.LayoutMethod" type="LayoutMethodType"/>
    <xs:attribute name="ClipContents" type="BooleanOrBindingType"/>
    
    <!-- Button Properties -->
    <xs:attribute name="Command.Click" type="xs:string"/>
    <xs:attribute name="ClickToActivate" type="BooleanOrBindingType"/>
    <xs:attribute name="IsSelected" type="BooleanOrBindingType"/>
    
    <!-- Scrollable Properties -->
    <xs:attribute name="ClipRect" type="xs:string"/>
    <xs:attribute name="InnerPanel" type="xs:string"/>
    <xs:attribute name="AutoHideScrollBarHandle" type="BooleanOrBindingType"/>
    <xs:attribute name="AutoHideScrollBars" type="BooleanOrBindingType"/>
    
    <!-- Advanced Properties -->
    <xs:attribute name="UsedNavigationMovements" type="xs:string"/>
    <xs:attribute name="GamepadNavigationIndex" type="xs:int"/>
    <xs:attribute name="IsAutoNavigationTarget" type="BooleanOrBindingType"/>
    <xs:attribute name="FocusableChildIndex" type="xs:int"/>
    
    <!-- Grid Properties -->
    <xs:attribute name="DefaultCellWidth" type="xs:float"/>
    <xs:attribute name="DefaultCellHeight" type="xs:float"/>
    <xs:attribute name="ColumnCount" type="xs:int"/>
    
    <!-- Tooltip -->
    <xs:attribute name="TooltipWidget" type="xs:string"/>
    
    <!-- Misc -->
    <xs:attribute name="AcceptDrop" type="BooleanOrBindingType"/>
    <xs:attribute name="AcceptDrag" type="BooleanOrBindingType"/>
    <xs:attribute name="CanEffectOtherWidgetsBrush" type="BooleanOrBindingType"/>
    <xs:attribute name="CircularClipEnabled" type="BooleanOrBindingType"/>
    <xs:attribute name="CircularClipRadius" type="xs:float"/>
    <xs:attribute name="CircularClipSmoothingRadius" type="xs:float"/>
    
    <!-- Allow any other attributes (must be last) -->
    <xs:anyAttribute processContents="lax"/>
  </xs:attributeGroup>
  
  <!-- Simple Types -->
  <xs:simpleType name="BooleanOrBindingType">
    <xs:union memberTypes="xs:boolean">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="@.*"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:union>
  </xs:simpleType>
  
  <xs:simpleType name="SizePolicyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Fixed"/>
      <xs:enumeration value="StretchToParent"/>
      <xs:enumeration value="CoverChildren"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="AlignmentType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Left"/>
      <xs:enumeration value="Right"/>
      <xs:enumeration value="Center"/>
      <xs:enumeration value="Top"/>
      <xs:enumeration value="Bottom"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="LayoutMethodType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="HorizontalLeftToRight"/>
      <xs:enumeration value="HorizontalRightToLeft"/>
      <xs:enumeration value="VerticalTopToBottom"/>
      <xs:enumeration value="VerticalBottomToTop"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== SolWayward/Bannerlord.Commander/Bannerlord.Commander/_Module/GUI/Prefabs/CommanderPrefabs.xml
<?xml version="1.0" encoding="utf-8"?>
<Prefab xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../schemas/gauntletui.xsd">
  
  <!-- Hero Editor Left Column Component -->
  <Widget Id="HeroEditor.InfoColumn">
    <Children>
      <HeroInfoColumn />
    </Children>
  </Widget>

  <!-- Hero Editor Center Column Component -->
  <Widget Id="HeroEditor.CharacterColumn">
    <Children>
      <HeroCharacterColumn />
    </Children>
  </Widget>

  <!-- Hero Editor Right Column Component -->
  <Widget Id="HeroEditor.SkillsColumn">
    <Children>
      <HeroSkillsColumn />
    </Children>
  </Widget>

</Prefab>
